### ISSUE TITLE
Accessibility report from play console

### ISSUE THREAD

**Issue by jbpratt** [MemeLabs/strims-android#45]
### Touch Target
- [ ] `gg​.strims​.android:id​/optionsButton` ![example](https://i.imgur.com/cgjsKWN.png)
- [ ] `gg​.strims​.android:id​/messageChatMessage` ![example](https://i.imgur.com/kFjaMb7.png)
- [ ] `gg​.strims​.android:id​/twitchClose` ![example](https://i.imgur.com/CE90yo4.png)
- [ ] `gg​.strims​.android:id​/goToBottom` ![example](https://i.imgur.com/8dza6JG.png)
- [ ] `gg​.strims​.android:id​/sendMessageButton`  ![example](https://i.imgur.com/AcgZ9xP.png)
- [ ] `gg​.strims​.android:id​/sendMessageText` ![example](https://i.imgur.com/DdTNaB6.png)
- [ ] `gg​.strims​.android:id​/usernameChatMessage` ![example](https://i.imgur.com/TAJSnhL.png)

### Screen reader label
- [ ] `gg​.strims​.android:id​/sendMessageButton`: This item may not have a label readable by screen readers. ![example](https://i.imgur.com/6GwxpiW.png)
- [ ] `gg​.strims​.android:id​/optionsButton`
- [ ] `gg​.strims​.android:id​/userListButton`
- [ ] `gg​.strims​.android:id​/recyclerViewChat`
- [ ] `gg​.strims​.android:id​/usernameChatMessage`: This clickable item's speakable text: "jbpratt:" is identical to that of 1 other item(s).

### Text and Image contrast
... todo ...

**Comment by ftwpala** [comment]
My comments are
   1. Move the profile and settings into a different place (Sidebar/side swipe menu)
   2. Move the emote icon on the left side of the text message

The reasoning behind this is: Emotes are the only thing that is connected to sending a message. Profile and settings aren't really connected to chatting or anything "sending message" related.

The size of the icons need to be tested see how they "feel"

On another note, if you go the way of a side-swipe menu, you can also move the "Streams, Chat, Login" buttons in there, so that way there's more space for the chat itself :)

**Comment by JMPC14** [comment]
Suggestions by @ftwpala have been implemented, added contentDescription to all ImageViews in latest PR.
